### ISSUE TITLE
--use-css-variables: true;

### ISSUE THREAD

**Issue by penguinencounter** [school-projects-org/p6-islam#2]
heya it's your friendly suggestion person here

---

CSS has "variables" - they work by assigning a value to a name starting with two hypens. It looks like this:

```css
.selector {
  --whatever-name-you-want: 1.2em;
  --a-color: #ffffff;
  --my-favorite-border-style: 2px solid red;
  --image: url("https://example.com/quae.png");
}
```

You can define variables that are usable on the whole page using the `:root` selector. Reference the defined values with `var(--name-of-variable)`.

```css
:root {
  --main-theme-color: #b080ff;
}
.whatever-element.you-want-to.style {
  background-color: var(--main-theme-color);
}
div.another.element {
  box-shadow: 4px 4px 0px var(--main-theme-color);
}
```

The advantage is you only have to change the color in one place and all usages of `var(...)` will automatically update. This is an example of the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

```css
/** something like this **/
:root {
  --main: /* main color */;
  --details: /* details color */;
  --other: /* other color */;
}
```

[MDN documentation (warning: very over-complicated)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)
